### ISSUE TITLE
Od kade se vadat informaciite za vozduhot

### ISSUE THREAD

**Issue by gorjan-mishevski** [SasPes/air-quality-mk#2]
Zdravo.
Gledam po linkovite deka se povikuva od http://airquality.moepp.gov.mk/
No nemozam da najdam nikade API, nitu pak nekoja dokumentacija. Dali znaesh slucajno kade mozam da gi najdam ovie resursi? Fala

**Comment by SasPes** [comment]
Nema nekakva dokumentacija od oficijalnata strana, vidi gi primerite od Kumanovo sto se vo Resources delot. 

Inaku ako sakas mozes da go koristis SkopjePulse API-to (https://skopjepulse.mk/restapi). Mene mi e na TODO da go implementiram, plus ima poveke merni stanici.

**Comment by gorjan-mishevski** [comment]
Fala ti @SasPes . Gi gleav ovie SkopjePulse samo treba da sme pretpazlivi, gledam imaat nivna iOS i Android applikacija, toa znaci moze komotno rate limit da udrat ako nekoj im konkurira. Zatoa i sakav ova od vladava da zemam. Ali toa e toa, strashno, treba covek vnatre da se ima za da ti kaze. Im pushtiv i email ali ne vrakaat. Ti pushtiv zvezda na proektov. Samo ovde moze da se vidi kolku tolku kako im raboti APi-to. Fala usthe ednash 🍺
